[features]
seeds = false
skip-lint = false
[programs.localnet]
betting_platform = "2NTiJusDD3jS5CehvWskRbQQvshceFeZfRZbzKDrURty"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/ironsoul/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
